# Generated by Django 2.0.7 on 2018-07-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradesheet', '0002_assignment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='gradesheet.Course'),
        ),
    ]
